### PR TITLE
feat(mineflayer): add commentBlocked regex and function

### PR DESCRIPTION
**Pull request by xMdb**

### CODE REVIEW

**Comment by xMdb** [comment]
to-do: censor messages

**Review by Jejebecarte — APPROVED** [review]
lgtm

**Comment by Jejebecarte** [comment]
Oh. I forgor. Censoring incoming messages from discord. I've set up the realtime listener.

**Comment by xMdb** [comment]
> Oh. I forgor. Censoring incoming messages from discord. I've set up the realtime listener.

Yep if you could do that it would be great 👍🏻

**Comment by Jejebecarte** [comment]
@xMdb

**Comment by xMdb** [comment]
LGTM

**Pull request merged**
